### ISSUE TITLE
Build Failure when upgrading to Latest Shopify API

### ISSUE THREAD

**Issue by Praveen2106** [Shopify/shopify-app-js#793]
# Issue summary
When upgrading from Shopify API 8.1.1 to 9.7.1, the following errors occur while building the application. 

```
node_modules/@shopify/shopify-api/runtime/crypto/crypto.d.ts:1:23 - error TS2688: Cannot find type definition file for '@cloudflare/workers-types'.

1 /// <reference types="@cloudflare/workers-types" />

node_modules/@shopify/shopify-api/runtime/http/types.d.ts:1:23 - error TS2688: Cannot find type definition file for '@cloudflare/workers-types'.

1 /// <reference types="@cloudflare/workers-types" />

```

However, no issues with "npm run dev". The application runs without any issues. 

- [ ] Upgraded to the latest version of the relevant packages
  - "@shopify/shopify-api": "^9.3.2"
  - "@shopify/shopify-app-express": "^4.1.1"
  - "@shopify/app": "^3.58.2"
  - "@shopify/cli": "^3.58.2"
  - Node version: 18.8.2
  - Operating system: Windows 10

Are there any changes needed when upgrading to the latest version? We could not find any documentation for the same,

**Comment by lizkenyon** [comment]
Hi there 👋 

Could you share what your package.json looks like?

**Comment by Praveen2106** [comment]
I've attached the package.json file below. Kindly let me know if you need anything else. Thanks!

[package.json](https://github.com/Shopify/shopify-app-js/files/15041842/package.json)

**Comment by eyoeldefare** [comment]
They seem to break everything every time they upgrade their libraries. Look at their libraries, its barely production grade.

**Comment by Praveen2106** [comment]
I upgraded to 9.7.2 and this issue is not found now. But from the changes, I could not see what fixed this.
