### ISSUE TITLE
TypeError: scopesArray.map is not a function

### ISSUE THREAD

**Issue by dongido001** [Shopify/shopify-app-js#93]
# Issue summary
In this shopify.js file of the CLI 3 template, I tried using the MongoDBSessionStorage session storage but I was getting an error:

/Users/*/projects/buyonecolective-main/node_modules/@shopify/shopify-api/lib/auth/scopes/index.js:18
2023-01-12 17:52:09 | backend  |             .map(function (scope) { return scope.trim(); })
2023-01-12 17:52:09 | backend  |              ^
2023-01-12 17:52:09 | backend  |
2023-01-12 17:52:09 | backend  | TypeError: scopesArray.map is not a function
2023-01-12 17:52:09 | backend  |     at new AuthScopes (/Users/*/projects/*-main/node_modules/@shopify/shopify-api/lib/auth/scopes/index.js:18:14)
2023-01-12 17:52:09 | backend  |     at Session.isActive (/Users/*/projects/*-main/node_modules/@shopify/shopify-api/lib/session/session.js:80:77)
2023-01-12 17:52:09 | backend  |     at /Users/*/projects/*-main/web/node_modules/@shopify/shopify-app-express/build/cjs/middlewares/validate-authenticated-session.js:57:79
2023-01-12 17:52:09 | backend  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-01-12 17:52:09 | backend  |
2023-01-12 17:52:09 | backend  | Node.js v18.12.1
2023-01-12 17:52:09 | backend  | [nodemon] app crashed - waiting for file changes before starting...
2023-01-12 17:52:09 | frontend | 18:52:09 [vite] http proxy error:

- `@shopify/shopify-app-*` package and version:
- 
- Node version:
18
- Operating system:
Mac OS

## Expected behavior

`shopify.validateAuthenticatedSession()` should not break the app. 
## Actual behavior
App crashes when calling `shopify.validateAuthenticatedSession()`

Issue is most likely from the `MongoDBSessionStorage` class. I tweaked it a bit and it worked for me. The way it returns the Session in the loadSession method does not seem right.

**Comment by xiguan00yu** [comment]
same error. Cannot be fixed even after upgrading @shopify/shopify-app-express to 1.2.0. 
@cjpwrs Could you provide more information? I'm interested in the way you did the restoration. thanks you.

**Comment by mkevinosullivan** [comment]
> Issue is most likely from the MongoDBSessionStorage class. I tweaked it a bit and it worked for me. The way it returns the Session in the loadSession method does not seem right.

@dongido001 Can you elaborate on this comment please?  What tweak did you apply to get it working for you?

**Comment by mkevinosullivan** [comment]
@cjpwrs @xiguan00yu What version of the `@shopify/shopify-app-session-storage-mongodb` package are you using?

**Comment by zaaack93** [comment]
I 'm facing the same issue , is there someone have a solution for this ?

**Comment by CamilaAlvarez** [comment]
I believe the issue is due to `@shopify/shopify-app-express` and `@shopify/shopify-app-session-storage-mongodb` using incompatible versions of `@shopify/shopify-api`. 
Try updating `@shopify/shopify-app-express` to 2.0.0

**Comment by TomTweakCommerce** [comment]
> I believe the issue is due to `@shopify/shopify-app-express` and `@shopify/shopify-app-session-storage-mongodb` using incompatible versions of `@shopify/shopify-api`. Try updating `@shopify/shopify-app-express` to 2.0.0

This solved it for me, great job @CamilaAlvarez !

**Comment by mkevinosullivan** [comment]
Fixes merged in and released with `@shopify/shopify-api@7.1.0` and `@shopify/shopify-app-express@2.1.1`
